### ISSUE TITLE
大佬您好！问题求助。

### ISSUE THREAD

**Issue by Upcreat** [windmaple/Gemma-Chinese-instruction-tuning#4]
在Kaggle中执行图片中的代码时，出现错误，如果安装tensorflow-text会强制将Keras3的卸载掉。
![image](https://github.com/windmaple/Gemma-Chinese-instruction-tuning/assets/83943594/1c47742c-fa73-4d54-92ed-e5b0b5d943ff)
![image](https://github.com/windmaple/Gemma-Chinese-instruction-tuning/assets/83943594/70c111e6-ba57-423d-aff4-39373534a2ec)

**Comment by windmaple** [comment]
装上tensorflow-text即可

`!pip install -q -U tensorflow-cpu tensorflow-text`

**Comment by Upcreat** [comment]
好的，我试下
